# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f09b85ca22a867b7e387ea4fba643ccdecf1e08e4033acfd6ed7ce0bf9ce49a72ed58f7a1da79899dc13e500be8887e8b75743651d487ae4a4d7a6cd37fe4243

test:
  secret_key_base: c188dbed92c0cc057b51210cdb529b16745c4e25bbd5260627ddbf976bb8a5352e116e299cb344ac8e903c7f58ff8d203b7868630655c4dbe519fd8a7456ed74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
